version: "3"

services:

  ckan:
    container_name: ckan
    image docker-ckan_ckan:${CKAN_RELEASE}
    env_file:
      - .env-prd
    links:
      - db
      - solr
      - redis
      - datapusher
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ckan_storage:/var/lib/ckan

  datapusher:
    container_name: datapusher
    image: docker-ckan_datapusher:${CKAN_RELEASE)
    ports:
      - "8800:8800"

  db:
    container_name: db
    image: docker-ckan_db:${CKAN_RELEASE}
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    image: docker-ckan_solr:${CKAN_RELEASE}

  redis:
    container_name: redis
    image: docker-ckan_redis:${CKAN_RELEASE}

volumes:
  ckan_storage:
  pg_data:
