version: "3"

services:

  ckan:
    container_name: ckan
    build:
      context: ckan/
    dockerfile: Dockerfile
    args:
      - TZ=${TZ}
    env_file:
      - .env
    links:
      - db
      - solr
      - redis
      - datapusher
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ckan_storage:/var/lib/ckan
    restart: always
    
  datapusher:
    container_name: datapusher
    build:t: datapusher/
    ports:
      - "8800:8800"
    restart: always
    
# Commented out to use Postgresql service
# db:
#    container_name: db
#    build:
#      context: postgresql/
#      args:
#        - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
#        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#    environment:
#      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#    volumes:
#      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    build:
      context: solr/
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index
    restart: always
    
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    
volumes:
  ckan_storage:
# Commented out - using postgresql service
# pg_data:
  solr_data:
